FROM docker.io/ubuntu:24.04

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -yq update \
  && apt-get -yq install \
    bash \
    curl \
    nano \
    wget \
    git \
    python3 \
    python3-venv \
    libgl1 \
    libglib2.0-0 \
  && apt-get -yq clean

RUN set -exu \
  && addgroup \
    --gid 1000 \
    sdwebui \
  && adduser \
    --uid 1000 \
    --ingroup sdwebui \
    --disabled-password \
    --gecos sdwebui \
    sdwebui

USER sdwebui
WORKDIR /home/sdwebui

COPY ./stable-diffusion-webui /home/sdwebui/stable-diffusion-webui

ENTRYPOINT ["/bin/bash"]
CMD ["/home/sdwebui/stable-diffusion-webui/webui.sh"]
